//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entityes
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestHistory
    {
        public int TestId { get; set; }
        public int UserId { get; set; }
        public string SubjectId { get; set; }
        public DateTime TestDate { get; set; }
        public int CorrectAnswer { get; set; }
        public int TotalQuestion { get; set; }
        public int Mark { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedAt { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime ModifiedAt { get; set; }
   
    }
}
